language: r
cache: packages

#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release

repos:
  CRAN: https://cloud.r-project.org
  
r_github_packages:
  - jimhester/covr
  
#after_failure:
#  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls(type = "all")'

notifications:
  email:
    on_success: change
    on_failure: change
